const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.HTMLElement,
		C3.Plugins.Arr,
		C3.Plugins.CV_Set,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Plugins.PlatformInfo,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Plugins.LocalStorage,
		C3.Plugins.EMI_INDO_sweetalert2,
		C3.Behaviors.Physics,
		C3.Plugins.AJAX,
		C3.Behaviors.skymenTrail,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.NinePatch.Cnds.HasTags,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.TiledBg.Cnds.HasTags,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.JavaScriptInEvents.E_game_Event12_Act1,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.System.Exps.lowercase,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedWriteLeaderboard,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.PlaygamaBridge.Exps.PlayerPhoto,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.PlaygamaBridge.Acts.ShowRewarded,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedRewarded,
		C3.JavaScriptInEvents.E_help_Event25_Act1,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.JavaScriptInEvents.E_help_Event26_Act1,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.JavaScriptInEvents.E_effect_Event4_Act1,
		C3.JavaScriptInEvents.E_effect_Event4_Act5,
		C3.JavaScriptInEvents.E_effect_Event5_Act1,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Spritefont2.Acts.SetEffectEnabled,
		C3.Plugins.PlaygamaBridge.Exps.PlayerName,
		C3.Plugins.PlaygamaBridge.Exps.PlayerId,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedReadData,
		C3.Plugins.PlaygamaBridge.Acts.ShowBanner,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.BBoxRight,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnAdvTrigger,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Exps.readValue,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.RemoveData,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedReadLeaderboard,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.SetAwake,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.E_newgrid_Event3_Act2,
		C3.JavaScriptInEvents.E_newgrid_Event3_Act3,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.JavaScriptInEvents.E_newgrid_Event6_Act1,
		C3.JavaScriptInEvents.E_leaderboard_Event1_Act1,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnWriteAction,
		C3.JavaScriptInEvents.E_leaderboard_Event4_Act2,
		C3.JavaScriptInEvents.E_leaderboard_Event5_Act1,
		C3.JavaScriptInEvents.E_leaderboard_Event5_Act2,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Exps.readLeaderboard,
		C3.JavaScriptInEvents.E_leaderboard_Event7_Act6,
		C3.JavaScriptInEvents.E_leaderboard_Event8_Act1,
		C3.JavaScriptInEvents.E_leaderboard_Event8_Act2,
		C3.JavaScriptInEvents.E_leaderboard_Event10_Act6,
		C3.JavaScriptInEvents.E_leaderboard_Event15_Act4,
		C3.JavaScriptInEvents.E_leaderboard_Event19_Act3,
		C3.JavaScriptInEvents.E_leaderboard_Event20_Act1,
		C3.JavaScriptInEvents.E_leaderboard_Event22,
		C3.JavaScriptInEvents.E_leaderboard_Event25_Act1,
		C3.Plugins.Sparsha_FirebaseSDK.Cnds.OnLoaded
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{XP: 0},
	{XP_Mask: 0},
	{XP_GUI: 0},
	{Chest: 0},
	{glass: 0},
	{Help_Icons: 0},
	{wordsArray: 0},
	{usedWords: 0},
	{Palette: 0},
	{GridArray: 0},
	{Basketball_Letters: 0},
	{Basketball_Letters_Right: 0},
	{Basketball_Words: 0},
	{HelpWords: 0},
	{Letter: 0},
	{isSelected: 0},
	{selfNum: 0},
	{isCorrect: 0},
	{sHeight: 0},
	{sWidth: 0},
	{WORD: 0},
	{wordIndex: 0},
	{fullWordIndex: 0},
	{COLOR: 0},
	{Item: 0},
	{Set: 0},
	{BG: 0},
	{Table: 0},
	{Touch: 0},
	{Dictionary: 0},
	{PlatformInfo: 0},
	{Head: 0},
	{is_Btn: 0},
	{Container: 0},
	{Bottom: 0},
	{Btns: 0},
	{Diamond: 0},
	{Browser: 0},
	{Audio: 0},
	{Icons: 0},
	{All_Text: 0},
	{Rotate: 0},
	{LevelUP: 0},
	{Checker: 0},
	{Cursor: 0},
	{Wiki: 0},
	{Avatar: 0},
	{Theme: 0},
	{isFinish: 0},
	{Container2: 0},
	{Themes: 0},
	{LocalStorage: 0},
	{Player_LVL: 0},
	{Menu_Themes: 0},
	{Season: 0},
	{sweetalert2: 0},
	{Physics: 0},
	{Floor_Mini_Games: 0},
	{isFalling: 0},
	{Cur_Letter_Num: 0},
	{Ball: 0},
	{Solid: 0},
	{Hoop: 0},
	{Hoop_Grid: 0},
	{Letter_Place: 0},
	{Basketball_Letter: 0},
	{Ball_UID: 0},
	{Shadows: 0},
	{Hoop_Effect: 0},
	{AJAX: 0},
	{Triangle: 0},
	{TrailRenderer: 0},
	{Trail: 0},
	{GlobalHistory: 0},
	{FirebaseRDBasic: 0},
	{FirebaseSDK: 0},
	{PlaygamaBridge: 0},
	{StartSelected: 0},
	{isLevelUP: 0},
	{CurNum: 0},
	{CurWord: 0},
	{MaxGridSize: 0},
	{MaxLevelPerCategory: 0},
	{GameCategory: 0},
	{wiki: 0},
	{UID: 0},
	{Selected: 0},
	{Limit: 0},
	{x: 0},
	{y: 0},
	{Color: 0},
	{Count: 0},
	{Index: 0},
	{isFound: 0},
	{count: 0},
	{Word: 0},
	{Num: 0},
	{Wiki_Word: 0},
	{xp: 0},
	{xp_required: 0},
	{level: 0},
	{rank_xp: 0},
	{rank_required: 0},
	{rank: 0},
	{rank_level: 0},
	{xp_multiplier: 0},
	{rank_multiplier: 0},
	{how: 0},
	{is_Subtract: 0},
	{Diamonds: 0},
	{Sound: 0},
	{State: 0},
	{Action: 0},
	{Timer: 0},
	{Letters: 0},
	{Num_Of_Letter: 0},
	{Cur_WORD: 0},
	{Text_Lenth: 0},
	{GOAAALS: 0},
	{startX: 0},
	{startY: 0},
	{endX: 0},
	{endY: 0},
	{isThrowing: 0},
	{uid: 0},
	{Cur_Letter: 0},
	{AAAAA: 0},
	{category: 0},
	{availableSize: 0},
	{gridSize: 0},
	{oldResetDate: 0},
	{todayDate: 0},
	{CurrentName: 0},
	{CurrentScore: 0},
	{CurrentGems: 0},
	{SEP: 0},
	{playerID: 0},
	{currentTab: 0},
	{refreshFlag: 0},
	{writesCount: 0},
	{silentRead: 0},
	{justWrote: 0},
	{achTimer: 0},
	{foundRank: 0},
	{writeRank: 0},
	{histIndex: 0},
	{histPlayerID: 0},
	{histTrigger: 0},
	{histTime: 0},
	{histDate: 0},
	{historyRank: 0},
	{historyTime: 0},
	{leaderboardOpen: 0},
	{name: 0},
	{score: 0},
	{gems: 0},
	{avatar: 0},
	{index: 0},
	{pid: 0},
	{achName: 0},
	{achPid: 0},
	{achRank: 0},
	{historyRank2: 0},
	{historyTime2: 0}
];

self.InstanceType = {
	XP: class extends self.ISpriteInstance {},
	XP_Mask: class extends self.ISpriteInstance {},
	XP_GUI: class extends self.ITiledBackgroundInstance {},
	Chest: class extends self.ISpriteInstance {},
	glass: class extends self.IHTMLElementInstance {},
	Help_Icons: class extends self.ISpriteInstance {},
	wordsArray: class extends self.IArrayInstance {},
	usedWords: class extends self.IArrayInstance {},
	Palette: class extends self.IArrayInstance {},
	GridArray: class extends self.IArrayInstance {},
	Basketball_Letters: class extends self.IArrayInstance {},
	Basketball_Letters_Right: class extends self.IArrayInstance {},
	Basketball_Words: class extends self.IArrayInstance {},
	HelpWords: class extends self.IArrayInstance {},
	Item: class extends self.ISpriteInstance {},
	Set: class extends self.IInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Table: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	PlatformInfo: class extends self.IInstance {},
	Head: class extends self.ISpriteInstance {},
	Container: class extends self.IWorldInstance {},
	Bottom: class extends self.ISpriteInstance {},
	Btns: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Icons: class extends self.ISpriteInstance {},
	All_Text: class extends self.ISpriteFontInstance {},
	Letter: class extends self.ISpriteFontInstance {},
	LevelUP: class extends self.ISpriteInstance {},
	Checker: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Wiki: class extends self.IHTMLElementInstance {},
	Avatar: class extends self.ISpriteInstance {},
	Container2: class extends self.IWorldInstance {},
	Themes: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Player_LVL: class extends self.ISpriteInstance {},
	Menu_Themes: class extends self.ISpriteInstance {},
	Season: class extends self.ISpriteInstance {},
	sweetalert2: class extends C3.Plugins.EMI_INDO_sweetalert2.Instance {},
	Floor_Mini_Games: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Solid: class extends self.ITiledBackgroundInstance {},
	Hoop: class extends self.ISpriteInstance {},
	Hoop_Grid: class extends self.ISpriteInstance {},
	Letter_Place: class extends self.ISpriteInstance {},
	Basketball_Letter: class extends self.ISpriteFontInstance {},
	Shadows: class extends self.ISpriteInstance {},
	Hoop_Effect: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Triangle: class extends self.ISpriteInstance {},
	Trail: class extends self.ISpriteInstance {},
	GlobalHistory: class extends self.IDictionaryInstance {},
	FirebaseRDBasic: class extends C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Instance {},
	FirebaseSDK: class extends C3.Plugins.Sparsha_FirebaseSDK.Instance {},
	PlaygamaBridge: class extends C3.Plugins.PlaygamaBridge.Instance {}
}