function k(b,a,c,d){b.v.ib(b.nb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.ze()._OnMessageFromDOM({type:"event",component:b.nb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.nb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Rb||(b.v.hd(b.Sd),b.Rb=!0)}window.bb=class{constructor(b,a){this.v=b;this.nb=a;this.Rb=!1;this.Sd=()=>this.La()}$c(){}La(){}};
window.kf=class{constructor(){this.Wc=-1}j(){-1!==this.Wc&&(self.clearTimeout(this.Wc),this.Wc=-1)}};"use strict";function aa(b,a){n(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.Pb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.vd}
window.jf=class extends self.bb{constructor(b,a){super(b,a);this.Pb=new Map;this.Dc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Dc&&d.parentElement.removeChild(d);this.Pb.delete(c)}],["set-visible",c=>{if(this.Dc){var d=this.Pb.get(c.elementId),e=d.vd;d.Bd?e.style.display=c.isVisible?"":"none":d.Re=!!c.isVisible}}],["update-position",c=>{if(this.Dc){var d=this.Pb.get(c.elementId),e=d.vd;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Bd||(d.Bd=!0,d.Re&&(e.style.display=""))}}],["update-state",c=>{v(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",
c=>{v(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ze?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.cf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let z=new Audio;
const ia={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.jb=class b{constructor(a){this.ca=a.ef;this.wa=null;this.ba="";this.Ya=a.bf;this.Db={};this.Ra=this.ua=null;this.Ob=[];this.J=this.na=null;this.Lc=!1;this.yd=0;this.sb=null;this.Xa=-1;this.Ve=()=>this.He();this.Wa=[];this.Xc=null;this.Td=[];this.A=a.Ud;this.Sb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ca=!1);this.ca&&ca&&(this.ca=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ca=!1;if("cordova"===
this.A&&this.ca)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.gb()?self.chrome.webview.addEventListener("message",c=>this.nd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.nd(c));this.Vb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.De(c));this.C("runtime","create-job-worker",()=>this.Ee());this.C("runtime","send-wrapper-extension-message",c=>this.Ke(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.ld(a)):this.ld(a)}j(){this.uc();this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}oe(){return ba&&"cordova"===this.A}qc(){const a=
navigator.userAgent;return ba&&pa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}me(){return w}ed(){return w&&pa.has(this.A)}gb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async ld(a){"macos-wkwebview"===this.A?this.kb({type:"ready"}):this.gb()&&(this.Ne(),this.Td=(await this.Ce()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Vb={};await this.ve();
for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Vb.hasOwnProperty(c)?a.$a[d]={Ze:!0,cf:this.Vb[c]}:this.ra.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.ra[c]))}a.jc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.hd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.af?this.ba=a.af:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.gf&&(this.Db=a.gf);
c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ge(d));this.sb=new self.pe(this);await ra(this.sb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Be(a,c.port2):
await this.Ae(a,c.port2)}wc(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Sb)return a=await this.Fb(d.Ye?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}kd(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.fb(),m=a.nf,p=window.cr_previewImageBlobs||this.ra,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Ud;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.sb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.mf,jobScheduler:{inputPort:B.Kc,outputPort:B.Rc,maxNumWorkers:B.Se},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Ya+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.oe(),isiOSWebView:this.qc(),isWebView2Wrapper:this.gb(),wrapperComponentIds:this.Td,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Be(a,c){const d=this.wc(a.ff);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ua.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ua.addEventListener("message",p);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.lc(d,this.ba,{type:"module",name:"Runtime",Ye:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jc||[],g=a.$a;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.A)for(let h=0,m=a.ic.length;h<
m;++h){const p=a.ic[h],q=p[0];if(q===a.Yc||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Ma(q)}this.ua.postMessage(Object.assign(this.kd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.Yc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...sa(this.sb)]);this.Ob=F.map(h=>new h(this));this.jd();ta(this.na);self.c3_callFunction=(h,m)=>{var p=this.na;return p.v.gd(p.nb,
"js-invoke-function",{name:h,params:m})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.ib("runtime","go-to-last-error-script"))}async Ae(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ob=F.map(g=>new g(this));this.jd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.jc)){var e=[...a.jc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.Yc;const f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await y(h),"preview"!==this.A||d[g]||this.od(g,"main script did not run to completion")}catch(m){this.od(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await y(h);"preview"===this.A&&"object"!==typeof self.hf.lf?
(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:oa}),ta(this.na),this.md(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}od(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}md(){this.Kb()}Kb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ee(){const a=await ua(this.sb);return{outputPort:a,transferables:[a]}}ze(){if(this.ca)throw Error("not available in worker mode");return this.Ra}ib(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}gd(a,c,d,e,f){const g=na++,h=new Promise((m,p)=>{H.set(g,{resolve:m,reject:p})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Fe(a);if("result"===c)this.Ie(a);else if("runtime-ready"===c)this.Je();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.md();else throw Error(`unknown message '${c}'`);
}Fe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ie(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}C(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Eb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}jd(){for(const a of this.Ob)if("runtime"===a.nb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}Ge(a){this.ib("debugger","message",a)}Je(){for(const a of this.Ob)a.$c()}static fb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static pd(a){qa=!!a}hd(a){this.Wa.push(a);this.Bc()}Me(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Wa.splice(a,1);this.Wa.length||this.uc()}Bc(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Ve))}uc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}He(){this.Xa=
-1;for(const a of this.Wa)a();this.Bc()}Ba(a){this.na.Ba(a)}Ka(a){this.na.Ka(a)}Ac(){this.na.Ac()}Ib(a){this.na.Ib(a)}ne(){return!!ia["audio/webm; codecs=opus"]}async Oe(a){a=await this.gd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Lc=!0;this.yd=a}le(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fd(a){return!this.le(a)}async Ma(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Sb&&this.fd(a))?(a.startsWith(this.ba)&&
(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async De(a){const c=a.filename;switch(a.as){case "text":return await this.ke(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}cd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ke(a){a=await this.cd(a);return await ja(a)}vc(){if(D.length&&!(8<=E)){E++;
var a=D.shift();this.we(a.filename,a.df,a.Xe)}}Fb(a){return new Promise((c,d)=>{D.push({filename:a,df:e=>{E--;this.vc();c(e)},Xe:e=>{E--;this.vc();d(e)}});this.vc()})}async we(a,c,d){try{const e=await this.cd(a),f=await ka(e);c(f)}catch(e){d(e)}}nd(a){if("entered-fullscreen"===a)b.pd(!0),I(this.na);else if("exited-fullscreen"===a)b.pd(!1),I(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Xc(a),this.Xc=null):"extension-message"===c?this.ib("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ke(a){this.kb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}kb(a){this.gb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ne(){window.moveTo=(a,c)=>{this.kb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=
(a,c)=>{this.kb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ce(){return this.gb()?new Promise(a=>{this.Xc=a;this.kb({type:"wrapper-init"})}):Promise.resolve()}async ve(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.ue(c,d));await Promise.all(a)}async ue(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Vb[a]=c.str;else{let d=await this.ye(c);d||(d=this.xe(c));this.ra[a]=d}}async ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}xe(a){a=this.Le(a);return this.te(a.data,a.$e)}Le(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{$e:a,data:d}}te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const J=self.jb;function va(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},ya={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}
function Ba(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ca(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await Ba(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Da(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ea=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ca(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function ta(b){b.xd=!0;b.Oc=b.v.pa();b.tb=b.v.ia()}function I(b){if(!b.$){var a=J.fb();a&&"any"!==b.Uc&&Ia(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.wd=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.Zb=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.Zb}}
function Pa(b){b.rd||(b.rd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Qa(b){b.qd||(b.qd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ra(b){await za(b.url)}
function Sa(b,a){b.zd=a.message;-1===b.Gc&&(b.Gc=setTimeout(()=>{b.Gc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.zd)},250))}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:J.fb(),innerWidth:b.pa(),innerHeight:b.ia()})}function Oa(b,a){b.Zb!==a&&((b.Zb=a)?b.v.uc():b.v.Bc(),k(b,"visibilitychange",{hidden:a}))}
function Ua(b,a,c){"Backspace"===c.key&&M(c);if(!b.$){var d=wa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}function Va(b,a,c,d){b.$||va(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function Wa(b){window!==window.top&&window.focus();Xa(b.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.yb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Va(b,d,c,xa),b.yb=c.buttons)}}
function Ya(b,a,c){if(!b.$&&!va(c)){var d=b.yb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},K);b.yb=c.buttons;Va(b,c.type,c,xa)}}
function O(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
K)}}function Za(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function $a(b,a,c,d){const e=b.pa(),f=b.ia();b.Za=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.fb()}):10>d&&cb(b,e,f,d+1)}
function cb(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>$a(b,a,c,d),48)}
function Ia(b){b=b.Uc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Eb(class extends self.bb{constructor(b){super(b,"runtime");this.Fd=!0;this.xd=!1;this.Za=-1;this.Uc="any";this.Zb=this.qd=this.rd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Ea=null;this.$=!1;this.zd="";this.Gc=-1;this.wd=!1;this.Oc=b.pa();this.tb=b.ia();this.da=this.Cb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Lc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Fd&&(e.style.display="",this.Fd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ja(d));b.C("runtime","raster-svg-image",d=>Ka(d));b.C("runtime",
"get-svg-image-size",d=>La(d));b.C("runtime","set-target-orientation",d=>{this.Uc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ma(d));b.C("runtime","go-to-script",d=>Ma(d));b.C("runtime","before-start-ticking",()=>Na(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Pa(this));b.C("runtime","enable-device-motion",()=>Qa(this));b.C("runtime","add-stylesheet",d=>Ra(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.re(d.duration)});b.C("runtime","export-to-video-progress",d=>Sa(this,d));b.C("runtime","exported-to-video",d=>{window.We({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.We({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Da(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);c.addEventListener("selectstart",M);c.addEventListener("gesturehold",
M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),c.addEventListener("pointerdown",M)):c.addEventListener("touchstart",M);this.yb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.xd){var d=this.pa();var e=this.ia();if(this.v.ed()){if(this.wd){if(this.Oc===
d&&e<this.tb){this.Cb=this.tb-e;Za(this,this.tb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,Za(this,e,this.Cb))}this.Oc=d;this.tb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.fb()});this.v.qc()&&(-1!==this.Za&&clearTimeout(this.Za),$a(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",d=>Ta(this,d));window.addEventListener("webkitfullscreenerror",d=>Ta(this,d));window.addEventListener("mozfullscreenerror",d=>Ta(this,d));if(b.qc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Da(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Sa=new Set;this.Xb=new WeakSet;this.va=!1}$c(){window.addEventListener("focus",()=>{k(this,"window-focus",null,ya)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},ya);this.yb=0});window.addEventListener("focusin",a=>{a=a.target;(Ea.has(a.tagName.toLowerCase())||Da(a))&&
k(this,"keyboard-blur",null,ya)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>Va(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Wa(a);N(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Wa(a);Ya(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Ya(this,
"pointermove",a)),window.addEventListener("mouseup",a=>Ya(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Wa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.Ac();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.me()&&!this.v.ed()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ia(){return this.v.ia()}Ac(){var b=[...this.Sa];this.Sa.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Sa.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Xb.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Sa.add(b)})}Ka(b){this.Sa.delete(b);this.Xb.add(b)}Ib(b){this.va=!!b}});"use strict";async function ra(b){if(b.Pe)throw Error("already initialised");b.Pe=!0;var a=b.xa.wc(("playable-ad"===b.xa.A?b.xa.Ya:"")+"dispatchworker.js");b.Fc=await b.xa.lc(a,b.mb,{name:"DispatchWorker"});a=new MessageChannel;b.Kc=a.port1;b.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Rc=await ua(b)}
function sa(b){return[b.Kc,b.Rc]}async function ua(b){const a=b.Gd.length;var c=b.xa.wc(("playable-ad"===b.xa.A?b.xa.Ya:"")+"jobworker.js");c=await b.xa.lc(c,b.mb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Gd.push(c);return e.port1}
self.pe=class{constructor(b){this.xa=b;this.mb=b.ba;this.mb="preview"===b.A?this.mb+"workers/":this.mb+b.Ya;this.Se=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Gd=[];this.Rc=this.Kc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.jb({ef:!1,ff:"workermain.js",$a:["scripts/c3runtime.js"],ic:[],Yc:"",bf:"scripts/",jc:[],Ud:"html5"}));"use strict";const db=180/Math.PI;
async function eb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.Vc=a.timeScaleMode;b.Ld=["equalpower","HRTF","soundfield"][a.panningModel];b.ud=["linear","inverse","exponential"][a.distanceModel];b.Md=a.refDistance;b.Kd=a.maxDistance;b.Od=a.rolloffFactor;if(b.v.Lc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.yd)});else{var c={latencyHint:a.latencyHint};b.Rd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");fb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&fb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function gb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Hd=g.slice(0);hb(b,g);try{b.R=await ib(b,c,d,e,g,f);if(q){Q(b.R,!0);var r=b.R,B=q.innerAngle,la=q.outerAngle,ma=q.outerGain;if(r.rb){kb(r,q.x,q.y,q.z,q.angle);var C=self.ab.se;r.sa[0]!==C(B)&&
(r.sa[0]=C(B),r.F.coneInnerAngle=C(B));r.sa[1]!==C(la)&&(r.sa[1]=C(la),r.F.coneOuterAngle=C(la));r.sa[2]!==ma&&(r.sa[2]=ma,r.F.coneOuterGain=ma)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof A&&0!==A?(R(b.R,!0),lb(b.R,A)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,m,p,x)}catch(yb){console.error("[Construct] Audio: error starting playback: ",yb);return}finally{c=g.join(" ");d=b.Ab.get(c);if(!d)throw Error("expected pending tag");d.Zc--;0===d.Zc&&(d.resolve(),b.Ab.delete(c))}u(b)}
async function mb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const h of S(b,c))if(!h.Qa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ia=d;h.Pa=g;h.Qd=a}T(b)}async function ob(b,a){const c=a.tags;a=a.rate;await nb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Ca())}async function pb(b,a){const c=a.tags;a=a.pos;await nb(b,c);for(const d of S(b,c))d.rc(a)}
async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function sb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.$d(b,...e);else if("delay"===c)d=new self.Yd(b,...e);else if("convolution"===c){var g=d=new self.Xd(b,f.ja,...e),h=a.bufferType;g.sd=a.bufferOriginalUrl;g.td=h}else if("flanger"===c)d=new self.ae(b,...e);else if("phaser"===
c)d=new self.ce(b,...e);else if("gain"===c)d=new self.be(b,...e);else if("stereopan"===c)d=new self.ee(b,...e);else if("tremolo"===c)d=new self.fe(b,...e);else if("ringmod"===c)d=new self.de(b,...e);else if("distortion"===c)d=new self.Zd(b,...e);else if("compressor"===c)d=new self.Wd(b,...e);else if("analyser"===c)d=new self.Vd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.la.get(h);p||(p=[],g.la.set(h,p));d.Ed=p.length;d.Tc=h;p.push(d);tb(g,h)}ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.fc=a.timeScale;b.Hc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Ib(b.va);b.Wb=a.masterVolume;b.Oa.gain.value=
b.Wb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>sb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>wb(b,f,c)));T(b)}
async function xb(b,a){try{const c=b.g.suspend(a.time);b.Dd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.ib("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>zb(d)),b.Dd=!0);await c}catch(c){zb(c)}}
function fb(b){b.Qb||(b.Jc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Qb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.eb()===c)return await Ab(g),g;if(f)return null;if(e&&(b.ac||b.Cd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Rd;e&&f&&(b.Cd=!0);c=!e||b.ac||f?new self.ie(b,a,c,d,e,f):new self.ge(b,a,c,d,e);b.ka.push(c);await Ab(c);b.Jd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Jd.add(a));return c}
function Bb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Cb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function tb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Db(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Pc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*Db(b,a){if(a)for(const c of b.H)Bb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Eb(b,a,c){return c?b.v.Oe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Bb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ib(b,a,c,d,e,f){for(const g of b.H)if(g.eb()===c&&(g.kc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Cc?new self.he(a.s,a,e):new self.je(a.s,a,e);b.H.push(e);return e}
function hb(b,a){a=a.join(" ");let c=b.Ab.get(a);if(!c){let d=null;c={Zc:0,promise:new Promise(e=>d=e),resolve:d};b.Ab.set(a,c)}c.Zc++}function nb(b,a){return(b=b.Ab.get((0===a.length?b.Hd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Na.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Gb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function ub(b){b.Mc||(b.Mc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.cb());k(b,"fxstate",{fxstate:a});b.Mc=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),lb(b,d));c.Play(m,p,q,0);a.isPlaying||c.hb();c.yc(a)}}}function zb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.bb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Qb=this.Jc=!1;this.ya=()=>{if(!this.Jc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Jc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Qb=!1)}};this.ka=[];this.H=[];this.R=null;this.Hd=[];this.Jd=new Set;this.Id=-1;this.Ab=new Map;this.Wb=1;this.va=!1;this.Vc=0;this.fc=1;this.Hc=0;this.Ld="HRTF";this.ud="inverse";this.Md=600;this.Kd=1E4;this.Od=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Cd=this.ac=!1;this.Rd=this.v.ne();this.la=new Map;this.Na=new Set;this.Dd=this.Mc=!1;this.Pc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Pc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Cb(this,this.Pc))};this.Nb=null;self.C3Audio_GetOutputStream=()=>{this.Nb||(this.Nb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Nb));return this.Nb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>eb(this,a)],["play",a=>gb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.hb():d.Hb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>mb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Oa.gain.value=this.Wb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ib(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Ib(this.va);for(const c of this.H)c.Lb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.sc(a)}],["set-playback-rate",a=>ob(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),lb(d,a)}],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);ub(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);tb(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Hc=a.gameTime;this.Id=a.tickCount;if(0!==this.Vc)for(var c of this.H)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&kb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>xb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Oa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.va}Ba(b){this.v.Ba(b)}Ka(b){this.v.Ka(b)}La(){for(var b of this.Na)b.La();
b=this.g.currentTime;for(var a of this.H)a.La(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.cb());k(this,"state",{tickCount:this.Id,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.Tc,index:c.Ed,peak:c.Va,rms:c.Nd,binCount:c.l.frequencyBinCount,freqBins:c.Ad}))});0===a.length&&0===this.Na.size&&this.Rb&&(this.v.Me(this.Sd),this.Rb=!1)}static se(b){return b*db}static dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static qe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.jb.Eb(self.ab);"use strict";function Ab(b){b.Ub||(b.Ub=b.xc());return b.Ub}self.ad=class{constructor(b,a,c,d,e){this.s=b;this.Ue=a;this.Ha=c;this.T=d;this.Qe=e;this.Cc="";this.Ub=null}j(){this.Ub=this.s=null}xc(){}V(){return this.s.V()}nc(){return this.Ue}eb(){return this.Ha}mc(){return this.T}za(){return this.Qe}ha(){}};"use strict";
self.ge=class extends self.ad{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Cc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.ub=this.vb=null;this.M.addEventListener("canplaythrough",()=>!0);this.zb=this.V().createGain();this.xb=null;this.M.addEventListener("canplay",()=>{this.vb&&(this.vb(),this.ub=this.vb=null);!this.xb&&this.M&&(this.xb=this.V().createMediaElementSource(this.M),this.xb.connect(this.zb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.ub&&(this.ub(f),this.ub=this.vb=null)})}j(){Fb(this.s,this);this.zb.disconnect();this.zb=null;this.xb.disconnect();this.xb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}xc(){return new Promise((b,a)=>{this.vb=b;this.ub=a;this.M.src=this.Ha})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Jb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.A&&a.fd(b.Ha)&&a.Sb)b.Da=await a.Fb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Kb(b){if(b.ja)return b.ja;b.ja=await Eb(b.s,b.Da,b.Te);b.Da=null}
self.ie=class extends self.ad{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Cc="webaudio";this.ja=this.Da=null;this.Te=!!f}j(){Fb(this.s,this);this.ja=this.Da=null;super.j()}async xc(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.rb!==a&&(b.rb=a,b.rb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Ld,b.F.distanceModel=b.s.ud,b.F.refDistance=b.s.Md,b.F.maxDistance=b.s.Kd,b.F.rolloffFactor=b.s.Od),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function R(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function lb(b,a){b.Tb&&b.Sc!==a&&(b.fa.pan.value=a,b.Sc=a)}function U(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.Pa=-1;b.G.gain.value=b.oc()}function Ib(b,a){a=!!a;b.Qa!==a&&(b.Qa=a,b.Lb())}
function kb(b,a,c,d,e){if(b.rb){var f=b.Ua,g=b.Ta,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Nc?b.s.Hc:performance.now()/1E3}
self.bd=class{constructor(b,a,c){this.s=b;this.P=a;this.oa=c;this.Mb=Lb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.rb=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Tb=!1;this.Sc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ia=1;this.Qa=!1;this.ma=1;b=this.s.Vc;this.Nc=1===b&&!this.za()||2===b;this.Pa=this.qa=-1;this.Qd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}ga(){return Cb(this.s,0<this.oa.length?this.oa[0]:"")}nc(){return this.P.nc()}eb(){return this.P.eb()}mc(){return this.P.mc()}za(){return this.P.za()}O(){}kc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ja(){}ha(){return this.P.ha()}Play(){}Aa(){}hb(){}Hb(){}La(b){-1!==this.Pa&&b>=this.Pa&&(this.Pa=-1,this.Qd&&this.Aa(),Gb(this.s,"fade-ended",this.oa,this.Mb))}oc(){const b=this.Ia;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Lb(){}sc(){}Ca(){}rc(){}tc(){}pc(){}cb(){var b=
this.Mb,a=this.oa,c=this.ha(),d=-1===this.Pa?this.Ia:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Qa,resumePosition:this.pc(),pan:f,stereoPan:this.fa?
this.Sc:null}}yc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Ib(this,b.isMuted)}};"use strict";
self.he=class extends self.bd{constructor(b,a,c){super(b,a,c);this.P.zb.connect(this.G);this.P.onended=()=>this.zc()}j(){this.Aa();this.P.zb.disconnect();super.j()}W(){return this.P.W()}zc(){this.I=!0;this.qa=-1;Gb(this.s,"ended",this.oa,this.Mb)}O(){return this.W().ended}kc(){return this.I?!0:this.O()}Ja(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.eb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.I=!1;this.Y=b;this.ma=1}Aa(){const b=this.W();b.paused||b.pause();this.s.Ka(b);this.I=!0;this.K=!1;this.qa=-1}hb(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.s.Ka(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.s.Ba(this.W()),this.K=!1)}Lb(){this.W().muted=this.Qa||this.Gb()}sc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ca(){let b=this.ma;this.Nc&&(b*=this.s.fc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ja()}tc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Ba(this.W()),this.ta=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.lb=null}
self.je=class extends self.bd{constructor(b,a,c){super(b,a,c);this.o=null;this.Yb=d=>this.zc(d);this.Ic=!0;this.lb=null;this.S=this.$b=this.bc=0;this.Qc=1}j(){this.Aa();W(this);this.Yb=null;super.j()}zc(b){this.K||this.ta||b.target!==this.lb||(this.I=this.Ic=!0,this.qa=-1,W(this),Gb(this.s,"ended",this.oa,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Ic}kc(){return!this.o||this.I?!0:this.O()}Ja(){let b;b=this.K?this.S:this.$b+(V(this)-this.bc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Qc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.lb=this.o;this.o.onended=this.Yb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Ic=!1;this.Y=b;this.ma=1;this.bc=V(this);this.$b=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}hb(){this.K||this.I||this.O()||(this.S=this.Ja(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,U(this,this.Ia),this.Ca(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.K=!1)}oc(){return super.oc()*this.Qc}Lb(){this.Qc=this.Qa||this.Gb()?0:1;U(this,this.Ia)}sc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Nc&&(b*=this.s.fc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.I||this.O()||(this.K?this.S=b:(this.hb(),this.S=
b,this.Hb()))}pc(){return this.S}tc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ja(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,U(this,this.Ia),this.Ca(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.ta=!1)}yc(b){super.yc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Ed=-1;this.T=this.Tc="";this.m=null}j(){this.g=null}N(){}U(){}cb(){return{type:this.T,tag:this.Tc,params:this.m}}}
self.$d=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.wb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.pb=X(this);this.pb.gain.value=c;this.u.connect(this.wb);this.u.connect(this.h);this.wb.connect(this.i);this.wb.connect(this.X);this.X.connect(this.pb);this.pb.connect(this.wb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.wb.disconnect();
this.X.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){const e=self.ab.dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.pb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.td=this.sd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ob=this.g.createConvolver();this.ob.normalize=c;this.ob.buffer=a;this.u.connect(this.ob);this.u.connect(this.h);this.ob.connect(this.i)}j(){this.u.disconnect();this.ob.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}cb(){const b=super.cb();b.bufferOriginalUrl=this.sd;b.bufferUrl="";b.bufferType=this.td;return b}};
self.ae=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.qb=X(this);this.qb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.qb);this.qb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.qb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.qb.gain,a/100,c,d)}}};
self.ce=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.be=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ab.dd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ee=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.fe=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.de=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Bb=X(this);this.Bb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Bb.gain);this.B.start(0);this.u.connect(this.Bb);this.u.connect(this.h);this.Bb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Bb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.dc=X(this);this.cc=X(this);b=d;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Ec=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ec[32768+e]=f,this.Ec[32768-
e-1]=-f;this.hc.curve=this.Ec;this.u.connect(this.dc);this.u.connect(this.h);this.dc.connect(this.hc);this.hc.connect(this.cc);this.cc.connect(this.i)}j(){this.u.disconnect();this.dc.disconnect();this.hc.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Wd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Vd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Ad=new Float32Array(this.l.frequencyBinCount);this.Pd=new Uint8Array(a);this.Nd=this.Va=0;b=this.s;b.Na.add(this);T(b)}j(){this.s.Na.delete(this);this.l.disconnect();super.j()}La(){this.l.getFloatFrequencyData(this.Ad);this.l.getByteTimeDomainData(this.Pd);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Pd[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.ab.qe;this.Va=c(this.Va);this.Nd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Mb(b,a){a=a.type;let c=!0;0===a?c=await Nb():1===a&&(c=await Ob());k(b,"permission-result",{type:a,result:c})}
async function Nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.jb.Eb(class extends self.bb{constructor(b){super(b,"touch");n(this,"request-permission",a=>Mb(this,a))}});"use strict";function Pb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}
function Qb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Rb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Sb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}async function Tb(){const b=await Ub();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}
async function Vb(b){if(!b.Ga)try{b.Ga=await navigator.wakeLock.request("screen"),b.Ga.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ga=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function Wb(b){const a=await Ub();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Ub(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Pb(b),Qb(b),Rb(b),Sb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.jb.Eb(class extends self.bb{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>Tb()],["request-wake-lock",()=>Vb(this)],["release-wake-lock",()=>{this.Ga&&(this.Ga.release(),this.Ga=null)}]]);window.addEventListener("resize",()=>Wb(this));this.Ga=null}});
