const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Date,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Behaviors.aekiro_button,
		C3.Plugins.aekiro_proui,
		C3.Plugins.Sparsha_FirestoreBasic,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.Sparsha_FirebaseAuth,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.CV_GFX,
		C3.Plugins.Browser,
		C3.Plugins.CV_MobileNotch,
		C3.Behaviors.bound,
		C3.Plugins.MixonGames_EasyGestures,
		C3.Behaviors.aekiro_checkbox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Sparsha_FirestoreBasic.Acts.UserGetDoc,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Sparsha_FirebaseAuth.Exps.picURL,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sparsha_FirebaseAuth.Exps.userName,
		C3.Plugins.Sparsha_FirestoreBasic.Cnds.OnGet,
		C3.Plugins.Sparsha_FirestoreBasic.Cnds.GetDocExist,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sparsha_FirestoreBasic.Acts.UserSetDoc,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sparsha_FirestoreBasic.Exps.readFieldValue,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.aekiro_button.Acts.SetIgnoreInput,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.Tags,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.aekiro_checkbox.Cnds.IsChecked,
		C3.Behaviors.aekiro_checkbox.Acts.SimulateClick,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sparsha_FirestoreBasic.Acts.UserRemoveDoc,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.aekiro_checkbox.Cnds.OnClicked,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.aekiro_button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestInstall,
		C3.Plugins.Sparsha_FirebaseAuth.Cnds.OnSignedIn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sparsha_FirebaseAuth.Acts.PopupOauthSafe,
		C3.Behaviors.aekiro_button.Acts.SimulateClick,
		C3.Plugins.Sparsha_FirebaseSDK.Cnds.OnLoaded
	];
};
self.C3_JsPropNameTable = [
	{Date: 0},
	{Month: 0},
	{Type: 0},
	{Month_State_BG: 0},
	{S_Height: 0},
	{Price: 0},
	{Tween: 0},
	{Month_State: 0},
	{Touch: 0},
	{Water: 0},
	{AJAX: 0},
	{Electric: 0},
	{Gas: 0},
	{ShowPopup: 0},
	{IsEmpty: 0},
	{Button: 0},
	{Base: 0},
	{ProUI: 0},
	{FirebaseV9FirestoreBasic: 0},
	{FirebaseV9SDK: 0},
	{FirebaseV9AuthBasic: 0},
	{btn_Login: 0},
	{Icons: 0},
	{Sprite: 0},
	{Text: 0},
	{s_Width: 0},
	{s_Height: 0},
	{isOpen: 0},
	{State: 0},
	{Month_Popup: 0},
	{IsSelect: 0},
	{Month_BG_Popup: 0},
	{Anchor: 0},
	{State_Dark: 0},
	{Avatar: 0},
	{GFX: 0},
	{Browser: 0},
	{MobileNotch: 0},
	{sel_Home: 0},
	{BoundToLayout: 0},
	{Popup_Price: 0},
	{EasyGestures: 0},
	{Buttons: 0},
	{Checkbox: 0},
	{b_Options: 0},
	{Popup_Download: 0},
	{IsOpen: 0},
	{Popup_Calculate: 0},
	{Values: 0},
	{BtnCalculate: 0},
	{HCS: 0},
	{CloseCalculate: 0},
	{BtnDownload: 0},
	{Day: 0},
	{Year: 0},
	{Type_Popup: 0}
];

self.InstanceType = {
	Date: class extends self.IInstance {},
	Month_State_BG: class extends self.ISpriteInstance {},
	Month_State: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Water: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Electric: class extends self.IArrayInstance {},
	Gas: class extends self.IArrayInstance {},
	Base: class extends self.ISpriteInstance {},
	ProUI: class extends self.IInstance {},
	FirebaseV9FirestoreBasic: class extends self.IInstance {},
	FirebaseV9SDK: class extends self.IInstance {},
	FirebaseV9AuthBasic: class extends self.IInstance {},
	btn_Login: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	State: class extends self.ISpriteInstance {},
	Month_Popup: class extends self.ISpriteInstance {},
	Month_BG_Popup: class extends self.ISpriteInstance {},
	State_Dark: class extends self.ISpriteInstance {},
	Avatar: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	GFX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MobileNotch: class extends self.IInstance {},
	sel_Home: class extends self.ISpriteInstance {},
	Popup_Price: class extends self.ISpriteInstance {},
	EasyGestures: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	b_Options: class extends self.ISpriteInstance {},
	Popup_Download: class extends self.ISpriteInstance {},
	Popup_Calculate: class extends self.ISpriteInstance {},
	Values: class extends self.ISpriteInstance {},
	BtnCalculate: class extends self.ISpriteInstance {},
	HCS: class extends self.ISpriteInstance {},
	CloseCalculate: class extends self.ISpriteInstance {},
	BtnDownload: class extends self.ISpriteInstance {}
}