const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Date,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerHasKey,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.NinePatch.Acts.SetZ,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.hexcolor,
		C3.Plugins.NinePatch.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.DrawingCanvas.Acts.ZMoveToObject,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Exps.AsJSON,
		C3.Plugins.DrawingCanvas.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.ZMoveToObject,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.DrawingCanvas.Acts.AddChild,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.OutlineRect,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Cnds.CompareX,
		C3.Plugins.DrawingCanvas.Cnds.CompareY,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.DrawingCanvas.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Cnds.IsOnScreen,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToLayer,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.DrawingCanvas.Cnds.HasChildren,
		C3.Plugins.DrawingCanvas.Cnds.PickChildren,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Cnds.CompareInstanceVar,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetFlag,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Exps.max,
		C3.Plugins.NinePatch.Cnds.HasTags,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsPost,
		C3.Plugins.Eponesh_GameScore.Exps.AppUrl,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Eponesh_GameScore.Exps.ServerTimeUnix,
		C3.Plugins.Date.Exps.Parse,
		C3.Plugins.Date.Exps.GetUTCYear,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.TiledBg.Acts.SetZ,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.TypeScriptInEvents.E_menu_Event3_Act1,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetchPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerField,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardPlayerPosition,
		C3.TypeScriptInEvents.E_menu_Event58_Act1,
		C3.TypeScriptInEvents.E_menu_Event65_Act1,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.TypeScriptInEvents.E_menu_Event72_Act1,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.JavaScriptInEvents.E_menu_Event77_Act1,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerReset,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.DrawingCanvas.Acts.SetPosToObject,
		C3.Plugins.Eponesh_GameScore.Cnds.IsDev,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Behaviors.Tween.Cnds.IsAnyPingPong,
		C3.JavaScriptInEvents.E_popup_Event11_Act1,
		C3.JavaScriptInEvents.E_popup_Event12_Act1,
		C3.JavaScriptInEvents.E_popup_Event13_Act1,
		C3.JavaScriptInEvents.E_popup_Event14_Act1,
		C3.JavaScriptInEvents.E_popup_Event15_Act1,
		C3.JavaScriptInEvents.E_popup_Event16_Act1,
		C3.JavaScriptInEvents.E_popup_Event17_Act1,
		C3.JavaScriptInEvents.E_popup_Event18_Act1,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAchievementsAnyUnlock,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Exps.Tags,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchPlayerRatingScoped,
		C3.JavaScriptInEvents.E_segments_Event2_Act1,
		C3.JavaScriptInEvents.E_segments_Event2_Act2,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Behaviors.Tween.Acts.SetTweensTime,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.ChangeTags,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Cnds.AppIsAlreadyReviewed,
		C3.Plugins.Eponesh_GameScore.Acts.AppRequestReview,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAppLastAddShortcutSuccess,
		C3.Plugins.Eponesh_GameScore.Acts.AppAddShortcut
	];
};
self.C3_JsPropNameTable = [
	{ignoreLangUpdate: 0},
	{sfBold: 0},
	{sfSemiBold: 0},
	{sfBold2xOutline: 0},
	{sfBold2x: 0},
	{Tween: 0},
	{Timer: 0},
	{puzzle: 0},
	{framePuzzle: 0},
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{startAngle: 0},
	{lastX: 0},
	{lastY: 0},
	{DragDrop: 0},
	{puzzlePiece: 0},
	{GridBlock: 0},
	{PickEffect: 0},
	{SplashGlow: 0},
	{Flash: 0},
	{Fade: 0},
	{WinGlow: 0},
	{GameManager: 0},
	{Anchor: 0},
	{BG: 0},
	{refImage: 0},
	{bg_2: 0},
	{orderCategories: 0},
	{Dictionary: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Touch: 0},
	{Browser: 0},
	{backToCat: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{w: 0},
	{h: 0},
	{Sine: 0},
	{btnFinish: 0},
	{catFrame: 0},
	{catFrameHeader: 0},
	{PlatformInfo: 0},
	{isOpen: 0},
	{catName: 0},
	{lvlsCompleted: 0},
	{price: 0},
	{catIndex: 0},
	{canBuy: 0},
	{baseY: 0},
	{Red: 0},
	{Green: 0},
	{Blue: 0},
	{Alpha: 0},
	{color: 0},
	{categoriesBtn: 0},
	{frameHeader: 0},
	{starGame: 0},
	{frameBottom: 0},
	{index: 0},
	{catImage: 0},
	{catLock: 0},
	{showBtn: 0},
	{Date: 0},
	{cover_image: 0},
	{cover_start: 0},
	{framePuzzleBottom: 0},
	{GamePush: 0},
	{showCounterBG: 0},
	{max: 0},
	{catProcentage: 0},
	{topPoint: 0},
	{Audio: 0},
	{backToMenu: 0},
	{Intro: 0},
	{btnMenu: 0},
	{dailyState: 0},
	{menuProgress: 0},
	{menuProgressIndicator: 0},
	{Leader: 0},
	{popup: 0},
	{popup_bg: 0},
	{starMenu: 0},
	{sharing: 0},
	{barHeight: 0},
	{optionBtn: 0},
	{soundBtn: 0},
	{socialBtn: 0},
	{JSON: 0},
	{support: 0},
	{tutorial_cursor: 0},
	{BS: 0},
	{popup_icons: 0},
	{info: 0},
	{segment: 0},
	{Segment: 0},
	{lineCurSegments: 0},
	{lineSegments: 0},
	{starSegment: 0},
	{Stickers: 0},
	{Rotate: 0},
	{lightSticker: 0},
	{stickersPack: 0},
	{segmentCircle: 0},
	{puzzlePieceFamily: 0},
	{allText: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{dailyImage: 0},
	{SnapDistance: 0},
	{curCategory: 0},
	{curLVL: 0},
	{maxLVL: 0},
	{lastOpened: 0},
	{curColor: 0},
	{shows: 0},
	{isDailyStart: 0},
	{DailyTimeSeconds: 0},
	{nextCat: 0},
	{nextLevel: 0},
	{found: 0},
	{level: 0},
	{prevCompleted: 0},
	{hasPlayable: 0},
	{isUnlock: 0},
	{contentHeight: 0},
	{tier: 0},
	{category: 0},
	{CurrentIndex: 0},
	{margin: 0},
	{x: 0},
	{y: 0},
	{Count: 0},
	{addCoin: 0},
	{nextCategory: 0},
	{count_debug: 0},
	{Duration: 0},
	{Strength: 0},
	{n10: 0},
	{n100: 0},
	{n: 0},
	{curScrollY: 0},
	{scrollVelocity: 0},
	{velocityStop: 0},
	{minScroll: 0},
	{maxScroll: 0},
	{isDraging: 0},
	{rubber: 0},
	{returnForce: 0},
	{delta: 0},
	{dailyPuzzleFinished: 0},
	{dayOfYear: 0},
	{curProgress: 0},
	{maxProgress: 0},
	{isDaily: 0},
	{isPlay: 0},
	{progressWidth: 0},
	{language: 0},
	{isPing: 0},
	{ping: 0},
	{step: 0},
	{isInfo: 0},
	{canTouch: 0},
	{isPopupShowing: 0},
	{top_text: 0},
	{bottom_text: 0},
	{icon: 0},
	{fontScale: 0},
	{Type: 0},
	{lastAdTime: 0},
	{key: 0},
	{darkColor: 0},
	{lightColor: 0},
	{segmentCount: 0},
	{curSegment: 0},
	{usableWidth: 0},
	{spacing: 0},
	{widthPercent: 0},
	{isGifted: 0},
	{positionY: 0},
	{coin: 0},
	{uid: 0}
];

self.InstanceType = {
	sfBold: class extends self.ISpriteFontInstance {},
	sfSemiBold: class extends self.ISpriteFontInstance {},
	sfBold2xOutline: class extends self.ISpriteFontInstance {},
	sfBold2x: class extends self.ISpriteFontInstance {},
	puzzle: class extends self.ISpriteInstance {},
	framePuzzle: class extends self.I9PatchInstance {},
	puzzlePiece: class extends self.IDrawingCanvasInstance {},
	GridBlock: class extends self.I9PatchInstance {},
	PickEffect: class extends self.I9PatchInstance {},
	SplashGlow: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	WinGlow: class extends self.IParticlesInstance {},
	GameManager: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	refImage: class extends self.IDrawingCanvasInstance {},
	bg_2: class extends self.ISpriteInstance {},
	orderCategories: class extends self.IArrayInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	backToCat: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	btnFinish: class extends self.I9PatchInstance {},
	catFrame: class extends self.I9PatchInstance {},
	catFrameHeader: class extends self.I9PatchInstance {},
	PlatformInfo: class extends self.IInstance {},
	categoriesBtn: class extends self.I9PatchInstance {},
	frameHeader: class extends self.I9PatchInstance {},
	starGame: class extends self.ISpriteInstance {},
	frameBottom: class extends self.I9PatchInstance {},
	catImage: class extends self.ISpriteInstance {},
	catLock: class extends self.ISpriteInstance {},
	showBtn: class extends self.ISpriteInstance {},
	Date: class extends self.IInstance {},
	cover_image: class extends self.IDrawingCanvasInstance {},
	cover_start: class extends self.ISpriteInstance {},
	framePuzzleBottom: class extends self.I9PatchInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	showCounterBG: class extends self.I9PatchInstance {},
	catProcentage: class extends self.ITiledBackgroundInstance {},
	topPoint: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	backToMenu: class extends self.ISpriteInstance {},
	Intro: class extends self.ISpriteInstance {},
	btnMenu: class extends self.I9PatchInstance {},
	dailyState: class extends self.ISpriteInstance {},
	menuProgress: class extends self.I9PatchInstance {},
	menuProgressIndicator: class extends self.ISpriteInstance {},
	Leader: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	popup_bg: class extends self.ITiledBackgroundInstance {},
	starMenu: class extends self.ISpriteInstance {},
	sharing: class extends self.IDrawingCanvasInstance {},
	optionBtn: class extends self.ISpriteInstance {},
	soundBtn: class extends self.ISpriteInstance {},
	socialBtn: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	support: class extends self.ISpriteInstance {},
	tutorial_cursor: class extends self.ISpriteInstance {},
	BS: class extends self.ITiledBackgroundInstance {},
	popup_icons: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	Segment: class extends self.ISpriteInstance {},
	lineCurSegments: class extends self.ISpriteInstance {},
	lineSegments: class extends self.ISpriteInstance {},
	starSegment: class extends self.ISpriteInstance {},
	Stickers: class extends self.ISpriteInstance {},
	lightSticker: class extends self.ISpriteInstance {},
	stickersPack: class extends self.IArrayInstance {},
	segmentCircle: class extends self.ISpriteInstance {},
	puzzlePieceFamily: class extends self.IDrawingCanvasInstance {},
	allText: class extends self.ISpriteFontInstance {}
}