const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Date,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.DrawingCanvas.Acts.SetPosToObject,
		C3.Plugins.DrawingCanvas.Acts.ZMoveToObject,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Exps.AsJSON,
		C3.Plugins.DrawingCanvas.Acts.SetOpacity,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.DrawingCanvas.Acts.AddChild,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.OutlineRect,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Cnds.CompareX,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.DrawingCanvas.Cnds.CompareY,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.DrawingCanvas.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Cnds.IsOnScreen,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToLayer,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Plugins.DrawingCanvas.Cnds.PickChildren,
		C3.Plugins.DrawingCanvas.Cnds.HasChildren,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.hexcolor,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Exps.WheelDeltaY
	];
};
self.C3_JsPropNameTable = [
	{categoriesText: 0},
	{gameText: 0},
	{txtTimer: 0},
	{Anchor: 0},
	{txtCoinGame: 0},
	{nextText: 0},
	{categoriesHeaderText: 0},
	{Tween: 0},
	{Timer: 0},
	{puzzle: 0},
	{framePuzzle: 0},
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{startAngle: 0},
	{lastX: 0},
	{lastY: 0},
	{DragDrop: 0},
	{puzzlePiece: 0},
	{GridBlock: 0},
	{PickEffect: 0},
	{SplashGlow: 0},
	{Flash: 0},
	{Fade: 0},
	{WinGlow: 0},
	{GameManager: 0},
	{BG: 0},
	{refImage: 0},
	{bg_2: 0},
	{orderCategories: 0},
	{Dictionary: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Touch: 0},
	{Browser: 0},
	{deleteBtn: 0},
	{backBtn: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{w: 0},
	{h: 0},
	{btnNext: 0},
	{catFrame: 0},
	{catFrameHeader: 0},
	{PlatformInfo: 0},
	{isOpen: 0},
	{catName: 0},
	{lvlsCompleted: 0},
	{price: 0},
	{catIndex: 0},
	{canBuy: 0},
	{baseY: 0},
	{Red: 0},
	{Green: 0},
	{Blue: 0},
	{Alpha: 0},
	{color: 0},
	{categoriesBtn: 0},
	{frameHeader: 0},
	{starIcon: 0},
	{frameBottom: 0},
	{index: 0},
	{catImage: 0},
	{catLock: 0},
	{showBtn: 0},
	{Date: 0},
	{cover_image: 0},
	{cover_start: 0},
	{counterShows: 0},
	{framePuzzleBottom: 0},
	{GamePush: 0},
	{showCounterBG: 0},
	{max: 0},
	{catProcentage: 0},
	{Family1: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{dailyImage: 0},
	{SnapDistance: 0},
	{curCategory: 0},
	{curLVL: 0},
	{maxLVL: 0},
	{lastOpened: 0},
	{curColor: 0},
	{shows: 0},
	{tier: 0},
	{category: 0},
	{level: 0},
	{CurrentIndex: 0},
	{margin: 0},
	{x: 0},
	{y: 0},
	{Count: 0},
	{nextCategory: 0},
	{Duration: 0},
	{Strength: 0},
	{prevCompleted: 0},
	{hasPlayable: 0},
	{isUnlock: 0},
	{curScrollY: 0},
	{scrollVelocity: 0},
	{velocityStop: 0},
	{minScroll: 0},
	{maxScroll: 0},
	{isDraging: 0},
	{rubber: 0},
	{returnForce: 0},
	{delta: 0}
];

self.InstanceType = {
	categoriesText: class extends self.ITextInstance {},
	gameText: class extends self.ITextInstance {},
	txtTimer: class extends self.ITextInstance {},
	txtCoinGame: class extends self.ITextInstance {},
	nextText: class extends self.ITextInstance {},
	categoriesHeaderText: class extends self.ITextInstance {},
	puzzle: class extends self.ISpriteInstance {},
	framePuzzle: class extends self.I9PatchInstance {},
	puzzlePiece: class extends self.IDrawingCanvasInstance {},
	GridBlock: class extends self.I9PatchInstance {},
	PickEffect: class extends self.I9PatchInstance {},
	SplashGlow: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	WinGlow: class extends self.IParticlesInstance {},
	GameManager: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	refImage: class extends self.IDrawingCanvasInstance {},
	bg_2: class extends self.ISpriteInstance {},
	orderCategories: class extends self.IArrayInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	deleteBtn: class extends self.ISpriteInstance {},
	backBtn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	btnNext: class extends self.I9PatchInstance {},
	catFrame: class extends self.I9PatchInstance {},
	catFrameHeader: class extends self.I9PatchInstance {},
	PlatformInfo: class extends self.IInstance {},
	categoriesBtn: class extends self.I9PatchInstance {},
	frameHeader: class extends self.I9PatchInstance {},
	starIcon: class extends self.ISpriteInstance {},
	frameBottom: class extends self.I9PatchInstance {},
	catImage: class extends self.ISpriteInstance {},
	catLock: class extends self.ISpriteInstance {},
	showBtn: class extends self.ISpriteInstance {},
	Date: class extends self.IInstance {},
	cover_image: class extends self.IDrawingCanvasInstance {},
	cover_start: class extends self.ISpriteInstance {},
	counterShows: class extends self.ITextInstance {},
	framePuzzleBottom: class extends self.I9PatchInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	showCounterBG: class extends self.I9PatchInstance {},
	catProcentage: class extends self.ITiledBackgroundInstance {},
	Family1: class extends self.IDrawingCanvasInstance {}
}