const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase,
		C3.Plugins.Text,
		C3.Plugins.Sparsha_FirebaseAuth,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.HTMLElement,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.Sparsha_FirebaseAuthExtended,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.PlaygamaBridge.Exps.PlayerName,
		C3.Plugins.PlaygamaBridge.Exps.PlayerId,
		C3.Plugins.Button.Cnds.HasTags,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedWriteLeaderboard,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedReadLeaderboard,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnWriteAction,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnAdvTrigger,
		C3.Plugins.TextBox.Acts.SetText,
		C3.JavaScriptInEvents.Egame_Event11_Act2,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Exps.readLeaderboard,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.Egame_Event13_Act5,
		C3.JavaScriptInEvents.Egame_Event13_Act6,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.TextBox.Exps.Tags,
		C3.JavaScriptInEvents.Egame_Event15,
		C3.JavaScriptInEvents.Egame_Event16,
		C3.Plugins.Sparsha_FirebaseSDK.Cnds.OnLoaded,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Button: 0},
	{TextInput: 0},
	{FirebaseSDK: 0},
	{FirebaseRDBasic: 0},
	{Text: 0},
	{FirebaseAuthBasic: 0},
	{Browser: 0},
	{Sprite: 0},
	{HTMLElement: 0},
	{PlaygamaBridge: 0},
	{FirebaseAuthPro: 0},
	{CurrentName: 0},
	{CurrentScore: 0},
	{CurrentGems: 0},
	{SEP: 0},
	{playerID: 0},
	{name: 0},
	{score: 0},
	{gems: 0},
	{avatar: 0},
	{index: 0}
];

self.InstanceType = {
	Button: class extends self.IButtonInstance {},
	TextInput: class extends self.ITextInputInstance {},
	FirebaseSDK: class extends C3.Plugins.Sparsha_FirebaseSDK.Instance {},
	FirebaseRDBasic: class extends C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Instance {},
	Text: class extends self.ITextInstance {},
	FirebaseAuthBasic: class extends C3.Plugins.Sparsha_FirebaseAuth.Instance {},
	Browser: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	PlaygamaBridge: class extends C3.Plugins.PlaygamaBridge.Instance {},
	FirebaseAuthPro: class extends C3.Plugins.Sparsha_FirebaseAuthExtended.Instance {}
}