const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase,
		C3.Plugins.Text,
		C3.Plugins.Sparsha_FirebaseAuth,
		C3.Plugins.Browser,
		C3.Plugins.HTMLElement,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.Sparsha_FirebaseAuthExtended,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Egame_Event1_Act1,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.RemoveData,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Button.Cnds.HasTags,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedWriteLeaderboard,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedReadLeaderboard,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnWriteAction,
		C3.JavaScriptInEvents.Egame_Event11_Act2,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnAdvTrigger,
		C3.Plugins.TextBox.Acts.SetText,
		C3.JavaScriptInEvents.Egame_Event12_Act2,
		C3.JavaScriptInEvents.Egame_Event12_Act3,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Exps.readLeaderboard,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.Egame_Event14_Act6,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.TextBox.Exps.Tags,
		C3.JavaScriptInEvents.Egame_Event16_Act2,
		C3.JavaScriptInEvents.Egame_Event16_Act3,
		C3.JavaScriptInEvents.Egame_Event18_Act6,
		C3.JavaScriptInEvents.Egame_Event24_Act4,
		C3.JavaScriptInEvents.Egame_Event28_Act3,
		C3.JavaScriptInEvents.Egame_Event29_Act1,
		C3.JavaScriptInEvents.Egame_Event31,
		C3.JavaScriptInEvents.Egame_Event34_Act1,
		C3.Plugins.Sparsha_FirebaseSDK.Cnds.OnLoaded,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Button: 0},
	{TextInput: 0},
	{FirebaseSDK: 0},
	{FirebaseRDBasic: 0},
	{Text: 0},
	{FirebaseAuthBasic: 0},
	{Browser: 0},
	{HTMLElement: 0},
	{PlaygamaBridge: 0},
	{FirebaseAuthPro: 0},
	{Keyboard: 0},
	{oldResetDate: 0},
	{todayDate: 0},
	{CurrentName: 0},
	{CurrentScore: 0},
	{CurrentGems: 0},
	{SEP: 0},
	{playerID: 0},
	{name: 0},
	{score: 0},
	{gems: 0},
	{avatar: 0},
	{index: 0},
	{pid: 0},
	{achName: 0},
	{achPid: 0},
	{achRank: 0},
	{historyRank: 0},
	{historyTime: 0},
	{currentTab: 0},
	{refreshFlag: 0},
	{writesCount: 0},
	{silentRead: 0},
	{justWrote: 0},
	{achTimer: 0},
	{foundRank: 0},
	{writeRank: 0},
	{histIndex: 0},
	{histPlayerID: 0},
	{histTrigger: 0},
	{histTime: 0},
	{histDate: 0}
];

self.InstanceType = {
	Button: class extends self.IButtonInstance {},
	TextInput: class extends self.ITextInputInstance {},
	FirebaseSDK: class extends C3.Plugins.Sparsha_FirebaseSDK.Instance {},
	FirebaseRDBasic: class extends C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Instance {},
	Text: class extends self.ITextInstance {},
	FirebaseAuthBasic: class extends C3.Plugins.Sparsha_FirebaseAuth.Instance {},
	Browser: class extends self.IInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	PlaygamaBridge: class extends C3.Plugins.PlaygamaBridge.Instance {},
	FirebaseAuthPro: class extends C3.Plugins.Sparsha_FirebaseAuthExtended.Instance {},
	Keyboard: class extends self.IInstance {}
}