const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.aekiro_scrollView,
		C3.Plugins.Audio,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Plugins.aekiro_proui,
		C3.Behaviors.aekiro_gameobject,
		C3.Behaviors.Bullet,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.TextBox,
		C3.Plugins.lostinmind_TWASDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.lostinmind_TWASDK.Acts.ImpactOccurred,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Exps.BBoxLeft,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.aekiro_proui.Acts.Init,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsJoinCommunity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.lostinmind_TWASDK.Acts.NotificationOccurred,
		C3.Plugins.Eponesh_GameScore.Cnds.AppCanAddShortcut,
		C3.Plugins.Eponesh_GameScore.Acts.AppAddShortcut,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAchievementsAnyUnlock,
		C3.ScriptsInEvents.Achievements_Event7_Act1,
		C3.ScriptsInEvents.Achievements_Event8_Act1,
		C3.ScriptsInEvents.Achievements_Event9_Act1,
		C3.ScriptsInEvents.Achievements_Event10_Act1,
		C3.ScriptsInEvents.Achievements_Event11_Act1,
		C3.ScriptsInEvents.Achievements_Event12_Act1,
		C3.ScriptsInEvents.Achievements_Event13_Act1,
		C3.ScriptsInEvents.Achievements_Event14_Act1,
		C3.Plugins.GamePush_Channels.Acts.Join,
		C3.Plugins.GamePush_Channels.Acts.UpdateChannel,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.GamePush_Channels.Cnds.OnEventMessage,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.GamePush_Channels.Exps.CurMessageText,
		C3.Plugins.TextBox.Acts.ScrollToBottom,
		C3.Plugins.GamePush_Channels.Acts.SendMessage
	];
};
self.C3_JsPropNameTable = [
	{bgs: 0},
	{payment_type: 0},
	{description: 0},
	{availability: 0},
	{price: 0},
	{selected: 0},
	{number: 0},
	{Твинанимация: 0},
	{Таймер: 0},
	{Players: 0},
	{touch: 0},
	{clicks: 0},
	{Local: 0},
	{money: 0},
	{Якорь: 0},
	{Tween: 0},
	{UI: 0},
	{ScrollView: 0},
	{base: 0},
	{names: 0},
	{Description: 0},
	{Buttons: 0},
	{panel: 0},
	{audio: 0},
	{type: 0},
	{menu_Description: 0},
	{GameScore: 0},
	{browser: 0},
	{date: 0},
	{ProUI: 0},
	{GameObject: 0},
	{swipe: 0},
	{player_price: 0},
	{price_text: 0},
	{Пуля: 0},
	{klicks_effect: 0},
	{bg_selection: 0},
	{title: 0},
	{Description_2: 0},
	{bg_price: 0},
	{AJAX: 0},
	{buying_effect: 0},
	{Array: 0},
	{Keyboard: 0},
	{names_2: 0},
	{name: 0},
	{Anchor: 0},
	{noob: 0},
	{info: 0},
	{authors: 0},
	{bonus_text: 0},
	{bg: 0},
	{logo: 0},
	{btn_Text: 0},
	{Mouse: 0},
	{coin_effect: 0},
	{GamePushChannels: 0},
	{TextInput: 0},
	{Timer: 0},
	{Type: 0},
	{timer_text: 0},
	{Price: 0},
	{TelegramMiniAppsSDK: 0},
	{strong_click: 0},
	{thousand: 0},
	{coins: 0},
	{monety_change: 0},
	{anim_Time: 0},
	{char_sel: 0},
	{first_game: 0},
	{s_Width: 0},
	{s_Height: 0},
	{width: 0},
	{BG_Sel: 0},
	{timer: 0},
	{data_end: 0}
];

self.InstanceType = {
	bgs: class extends self.ISpriteInstance {},
	Players: class extends self.ISpriteInstance {},
	touch: class extends self.IInstance {},
	clicks: class extends self.ITextInstance {},
	Local: class extends self.IInstance {},
	money: class extends self.ITextInstance {},
	UI: class extends self.ISpriteInstance {},
	base: class extends self.ITiledBackgroundInstance {},
	names: class extends self.ITextInstance {},
	Description: class extends self.ITextInstance {},
	Buttons: class extends self.ISpriteInstance {},
	panel: class extends self.ISpriteInstance {},
	audio: class extends self.IInstance {},
	menu_Description: class extends self.ITextInstance {},
	GameScore: class extends self.IInstance {},
	browser: class extends self.IInstance {},
	date: class extends self.IInstance {},
	ProUI: class extends self.IInstance {},
	swipe: class extends self.ITiledBackgroundInstance {},
	player_price: class extends self.ISpriteInstance {},
	price_text: class extends self.ITextInstance {},
	klicks_effect: class extends self.ITextInstance {},
	bg_selection: class extends self.ISpriteInstance {},
	title: class extends self.ITextInstance {},
	Description_2: class extends self.ITextInstance {},
	bg_price: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	buying_effect: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	names_2: class extends self.ITextInstance {},
	name: class extends self.ISpriteInstance {},
	noob: class extends self.ISpriteInstance {},
	info: class extends self.ITiledBackgroundInstance {},
	authors: class extends self.ISpriteInstance {},
	bonus_text: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	btn_Text: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	coin_effect: class extends self.ISpriteInstance {},
	GamePushChannels: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Timer: class extends self.ISpriteInstance {},
	timer_text: class extends self.ITextInstance {},
	Price: class extends self.ISpriteInstance {},
	TelegramMiniAppsSDK: class extends self.C3.Plugins.lostinmind_TWASDK.Instance {}
}