const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.JavaScriptInEvents.E_game_Event2_Act1,
		C3.JavaScriptInEvents.E_game_Event3_Act1,
		C3.JavaScriptInEvents.E_game_Event4_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Browser.Acts.Alert,
		C3.JavaScriptInEvents.E_game_Event7_Act1,
		C3.JavaScriptInEvents.E_game_Event8_Act1,
		C3.JavaScriptInEvents.E_game_Event11_Act1,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.HasTags,
		C3.JavaScriptInEvents.E_game_Event38_Act1,
		C3.JavaScriptInEvents.E_game_Event39_Act1,
		C3.JavaScriptInEvents.E_game_Event40_Act1,
		C3.JavaScriptInEvents.E_game_Event41_Act1,
		C3.JavaScriptInEvents.E_game_Event42_Act1,
		C3.JavaScriptInEvents.E_game_Event43_Act1,
		C3.JavaScriptInEvents.E_game_Event44_Act1,
		C3.JavaScriptInEvents.E_game_Event45_Act1,
		C3.JavaScriptInEvents.E_game_Event47_Act2,
		C3.JavaScriptInEvents.E_game_Event47_Act3,
		C3.JavaScriptInEvents.E_game_Event47_Act4,
		C3.JavaScriptInEvents.E_game_Event47_Act5,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.JavaScriptInEvents.E_game_Event47_Act8,
		C3.JavaScriptInEvents.E_game_Event49_Act2,
		C3.JavaScriptInEvents.E_game_Event49_Act3,
		C3.JavaScriptInEvents.E_game_Event49_Act4,
		C3.JavaScriptInEvents.E_game_Event49_Act5,
		C3.JavaScriptInEvents.E_game_Event49_Act6,
		C3.JavaScriptInEvents.E_game_Event49_Act8,
		C3.JavaScriptInEvents.E_game_Event50_Act1,
		C3.JavaScriptInEvents.E_game_Event51_Act1,
		C3.JavaScriptInEvents.E_game_Event52_Act1,
		C3.JavaScriptInEvents.E_game_Event53_Act1,
		C3.JavaScriptInEvents.E_game_Event54_Act1,
		C3.JavaScriptInEvents.E_game_Event55_Act1,
		C3.JavaScriptInEvents.E_game_Event56_Act1,
		C3.JavaScriptInEvents.E_game_Event57_Act1,
		C3.JavaScriptInEvents.E_game_Event58_Act1,
		C3.JavaScriptInEvents.E_game_Event59_Act1,
		C3.JavaScriptInEvents.E_game_Event60_Act1,
		C3.JavaScriptInEvents.E_game_Event61_Act1,
		C3.JavaScriptInEvents.E_game_Event62_Act1,
		C3.Plugins.TextBox.Acts.SetText,
		C3.JavaScriptInEvents.E_game_Event63_Act2,
		C3.JavaScriptInEvents.E_game_Event64_Act1,
		C3.JavaScriptInEvents.E_game_Event65_Act2,
		C3.JavaScriptInEvents.E_game_Event66_Act1,
		C3.JavaScriptInEvents.E_game_Event67_Act1,
		C3.JavaScriptInEvents.E_game_Event68_Act1,
		C3.JavaScriptInEvents.E_game_Event69_Act1,
		C3.JavaScriptInEvents.E_game_Event70_Act1,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.E_init_Event1_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.JavaScriptInEvents.E_init_Event3_Act1
	];
};
self.C3_JsPropNameTable = [
	{Button: 0},
	{TitleText: 0},
	{ads: 0},
	{Browser: 0},
	{chat: 0},
	{Tween: 0},
	{testTouchWithMock: 0},
	{Touch: 0},
	{coins: 0},
	{level: 0},
	{playerCurName: 0},
	{language: 0},
	{sound: 0},
	{name: 0},
	{tag: 0},
	{text: 0},
	{playerName: 0},
	{platform: 0},
	{count: 0},
	{day: 0},
	{streak: 0},
	{id: 0},
	{title: 0}
];

self.InstanceType = {
	Button: class extends self.IButtonInstance {},
	TitleText: class extends self.ITextInstance {},
	ads: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	chat: class extends self.ITextInputInstance {},
	testTouchWithMock: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}